version: '3'

services:
  # Backend app
  pronom-backend:
    image: ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/pronom-backend:0.0.1
    ports:
      - "8080:80"
    environment:
      - MARKDOWN_DIR=/md
      - TRIPLESTORE=http://triplestore:3030/ds
    volumes:
      - ${PWD}/../backend/md:/md
    restart: on-failure
    depends_on:
      - triplestore
    networks:
      - pronom-net
  
  # Triplestore
  triplestore:
    image: ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/pronom-triplestore:0.0.1
    user: "9008:0"
    ports:
      - "8030:3030"
    environment:
      - ADMIN_PASSWORD=admin
    restart: on-failure
    networks:
      - pronom-net
  
  # Container-signature conversion script
  # Simplest way to run is to uncomment the following lines and run docker-compose from the rdf-conversion directory
  # The xml and csv files should be placed in rdf-conversion/data
  # Like so:
  # $ cd rdf-conversion
  # $ docker-compose -f ../deployment/docker-compose.yaml up container-signature-converter
  container-signature-converter:
    image: ${AWS_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/pronom-backend:0.0.1
    command: java -jar /pronombackend.jar convert-container-signatures /data/container-signatures.xml /data/puids.csv /out/container_signatures.ttl
    volumes:
      - ${PWD}/data/puid-lookup.csv:/data/puids.csv
      - ${PWD}/data/container-signature-20211216.xml:/data/container-signatures.xml
      - ${PWD}/out:/out

networks:
  pronom-net:
